from tests.EnvFullTest import *
from tests.EnvMinimalTest import *
from tests.LookUpTest import *
from tests.MCTSTest import *
from tests.ModelRatingTest import *
from tests.GameTest import *
#from tests.CombineTest import *
from tests.SolverTest import *
from tests.KerasModelTest import *
from tests.TinyDnnTest import *